### PR TITLE
fix: error on array of multiline string

### LINKED ISSUE #33: bug: unable to parse array of multiline string
Currently parsing array of multiline strings results in the following error:
``` bash
luajit: /usr/local/share/lua/5.1/tinyyaml.lua:350: attempt to compare number with nil
stack traceback:
        /usr/local/share/lua/5.1/tinyyaml.lua:350: in function 'parsescalar'
        /usr/local/share/lua/5.1/tinyyaml.lua:608: in function 'parseseq'
        /usr/local/share/lua/5.1/tinyyaml.lua:747: in function 'parsemap'
        /usr/local/share/lua/5.1/tinyyaml.lua:807: in function 'parsedocuments'
        /usr/local/share/lua/5.1/tinyyaml.lua:832: in function 'parse'
        main.lua:13: in main chunk
        [C]: at 0x55889d95bcd0
```
Below is the minimal code to reproduce the bug:
``` lua
local yaml = require("tinyyaml")

local yaml_config = [[
array_of_multiline_strings:
    - |
       testing first 
       string
    - |
       testing second
       string
]]

local debug_yaml_new = yaml.parse(yaml_config)
if not debug_yaml_new then
    print("failed to parse the content of file ")
    return
end
print("success!")
```
Related issue: (Original reporter) - https://github.com/apache/apisix/issues/10140

### PR DESCRIPTION
**Pull request by Revolyssup**
Fixes #33 
Test case added
Fix taken from https://github.com/apache/apisix/issues/10140#issuecomment-1702463400

### CODE REVIEW

File: spec/array_multiline_string_spec.lua [hunk 1]
```diff
@@ -0,0 +1,31 @@
+local busted = require('busted')
+local assert = require 'luassert'
+local yaml = require 'tinyyaml'
```
Comment (leslie-tsang) [inline spec/array_multiline_string_spec.lua:3]:
```suggestion
local busted = require('busted')
local assert = require('luassert')
local yaml   = require('tinyyaml')
```

File: tinyyaml.lua [hunk 2]
```diff
@@ -611,8 +611,10 @@ function Parser:parseseq(line, lines, indent)
       error("did not find expected alphabetic or numeric character")
     elseif rest then
       -- Array entry with a value
+      local nextline = lines[1]
+      local indent2 = countindent(nextline)
       tremove(lines, 1)
-      tinsert(seq, self:parsescalar(rest, lines))
+      tinsert(seq, self:parsescalar(rest, lines,indent2))
```
Comment (leslie-tsang) [inline tinyyaml.lua:617]:
```suggestion
      tinsert(seq, self:parsescalar(rest, lines, indent2))
```

**Review by leslie-tsang — APPROVED** [review]
